version: "3"
services:
  eleventy:
    image: node:16-slim
    volumes:
      - ${PWD}/node_modules
      - ${PWD}:/app
    working_dir: /app
    # environment:
    #   - DEBUG=Eleventy*
    ports:
      - 8080:8080
    command: /bin/bash -c "npm install && npx eleventy --watch --serve"
